// <auto-generated />
using System;
using LawyerBasket.ProfileService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LawyerBasket.ProfileService.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251203171512_Outbox")]
    partial class Outbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LawyerBasket.ProfileService.Domain.Entities.Academy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Degree")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LawyerProfileId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LawyerProfileId");

                    b.ToTable("Academy");
                });

            modelBuilder.Entity("LawyerBasket.ProfileService.Domain.Entities.Address", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("CityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserProfileId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("UserProfileId")
                        .IsUnique();

                    b.ToTable("Address");
                });

            modelBuilder.Entity("LawyerBasket.ProfileService.Domain.Entities.Certificates", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateReceived")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LawyerProfileId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LawyerProfileId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("LawyerBasket.ProfileService.Domain.Entities.City", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            Id = "b1e2c3d4-0001-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Adana"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0002-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Adıyaman"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0003-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Afyonkarahisar"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0004-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ağrı"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0005-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Amasya"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0006-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ankara"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0007-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Antalya"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0008-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Artvin"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0009-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Aydın"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0010-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Balıkesir"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0011-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bilecik"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0012-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bingöl"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0013-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bitlis"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0014-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bolu"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0015-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Burdur"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0016-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bursa"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0017-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Çanakkale"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0018-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Çankırı"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0019-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Çorum"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0020-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Denizli"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0021-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Diyarbakır"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0022-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Edirne"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0023-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Elazığ"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0024-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Erzincan"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0025-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Erzurum"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0026-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Eskişehir"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0027-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Gaziantep"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0028-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Giresun"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0029-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Gümüşhane"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0030-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Hakkari"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0031-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Hatay"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0032-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Isparta"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0033-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Mersin"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0034-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "İstanbul"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0035-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "İzmir"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0036-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Kars"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0037-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Kastamonu"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0038-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Kayseri"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0039-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Kırklareli"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0040-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Kırşehir"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0041-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Kocaeli"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0042-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Konya"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0043-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Kütahya"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0044-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Malatya"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0045-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Manisa"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0046-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Kahramanmaraş"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0047-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Mardin"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0048-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Muğla"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0049-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Muş"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0050-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Nevşehir"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0051-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Niğde"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0052-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ordu"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0053-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Rize"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0054-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sakarya"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0055-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Samsun"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0056-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Siirt"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0057-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sinop"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0058-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sivas"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0059-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tekirdağ"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0060-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tokat"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0061-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Trabzon"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0062-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tunceli"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0063-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Şanlıurfa"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0064-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Uşak"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0065-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Van"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0066-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Yozgat"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0067-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Zonguldak"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0068-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Aksaray"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0069-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bayburt"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0070-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Karaman"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0071-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Kırıkkale"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0072-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Batman"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0073-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Şırnak"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0074-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bartın"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0075-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ardahan"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0076-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Iğdır"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0077-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Yalova"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0078-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Karabük"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0079-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Kilis"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0080-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Osmaniye"
                        },
                        new
                        {
                            Id = "b1e2c3d4-0081-4f5a-8c9b-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Düzce"
                        });
                });

            modelBuilder.Entity("LawyerBasket.ProfileService.Domain.Entities.Contact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AlternateEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AlternatePhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LawyerProfileId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LawyerProfileId")
                        .IsUnique();

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("LawyerBasket.ProfileService.Domain.Entities.Experience", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LawyerProfileId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LawyerProfileId");

                    b.ToTable("Experience");
                });

            modelBuilder.Entity("LawyerBasket.ProfileService.Domain.Entities.Expertisement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Expertisement");

                    b.HasData(
                        new
                        {
                            Id = "e1a2b3c4-0001-4f5a-8c9d-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Criminal Law",
                            Name = "Ceza Hukuku"
                        },
                        new
                        {
                            Id = "e1a2b3c4-0002-4f5a-8c9d-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Commercial / Corporate Law",
                            Name = "Ticaret / Şirketler Hukuku"
                        },
                        new
                        {
                            Id = "e1a2b3c4-0003-4f5a-8c9d-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Labor / Employment Law",
                            Name = "İş Hukuku"
                        },
                        new
                        {
                            Id = "e1a2b3c4-0004-4f5a-8c9d-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Family Law",
                            Name = "Aile Hukuku"
                        },
                        new
                        {
                            Id = "e1a2b3c4-0005-4f5a-8c9d-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Inheritance Law",
                            Name = "Miras Hukuku"
                        },
                        new
                        {
                            Id = "e1a2b3c4-0006-4f5a-8c9d-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Real Estate Law",
                            Name = "Gayrimenkul / Emlak Hukuku"
                        },
                        new
                        {
                            Id = "e1a2b3c4-0007-4f5a-8c9d-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Intellectual Property Law",
                            Name = "Fikri Mülkiyet Hukuku"
                        },
                        new
                        {
                            Id = "e1a2b3c4-0008-4f5a-8c9d-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tax Law",
                            Name = "Vergi Hukuku"
                        },
                        new
                        {
                            Id = "e1a2b3c4-0009-4f5a-8c9d-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Administrative Law",
                            Name = "İdare Hukuku"
                        },
                        new
                        {
                            Id = "e1a2b3c4-0010-4f5a-8c9d-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "International Law",
                            Name = "Uluslararası Hukuk"
                        });
                });

            modelBuilder.Entity("LawyerBasket.ProfileService.Domain.Entities.Gender", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Gender");

                    b.HasData(
                        new
                        {
                            Id = "c1d2e3f4-0001-4a5b-8c9d-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Erkek",
                            Name = "Erkek"
                        },
                        new
                        {
                            Id = "c1d2e3f4-0002-4a5b-8c9d-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kadın",
                            Name = "Kadın"
                        },
                        new
                        {
                            Id = "c1d2e3f4-0003-4a5b-8c9d-1a2b3c4d5e6f",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Belirtmek İstemiyorum",
                            Name = "Belirtmek İstemiyorum"
                        });
                });

            modelBuilder.Entity("LawyerBasket.ProfileService.Domain.Entities.LawyerExpertisement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpertisementId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LawyerProfileId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExpertisementId");

                    b.HasIndex("LawyerProfileId");

                    b.ToTable("LawyerExpertisement");
                });

            modelBuilder.Entity("LawyerBasket.ProfileService.Domain.Entities.LawyerProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("About")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("BarAssociation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("BarNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LicenseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserProfileId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId")
                        .IsUnique();

                    b.ToTable("LawyerProfile");
                });

            modelBuilder.Entity("LawyerBasket.ProfileService.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<int>("MyProperty")
                        .HasColumnType("integer");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("LawyerBasket.ProfileService.Domain.Entities.UserProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("LawyerBasket.ProfileService.Domain.Entities.Academy", b =>
                {
                    b.HasOne("LawyerBasket.ProfileService.Domain.Entities.LawyerProfile", "LawyerProfile")
                        .WithMany("Academy")
                        .HasForeignKey("LawyerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LawyerProfile");
                });

            modelBuilder.Entity("LawyerBasket.ProfileService.Domain.Entities.Address", b =>
                {
                    b.HasOne("LawyerBasket.ProfileService.Domain.Entities.City", "City")
                        .WithMany("Address")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LawyerBasket.ProfileService.Domain.Entities.UserProfile", "UserProfile")
                        .WithOne("Address")
                        .HasForeignKey("LawyerBasket.ProfileService.Domain.Entities.Address", "UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("LawyerBasket.ProfileService.Domain.Entities.Certificates", b =>
                {
                    b.HasOne("LawyerBasket.ProfileService.Domain.Entities.LawyerProfile", "LawyerProfile")
                        .WithMany("Certificates")
                        .HasForeignKey("LawyerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LawyerProfile");
                });

            modelBuilder.Entity("LawyerBasket.ProfileService.Domain.Entities.Contact", b =>
                {
                    b.HasOne("LawyerBasket.ProfileService.Domain.Entities.LawyerProfile", "LawyerProfile")
                        .WithOne("Contact")
                        .HasForeignKey("LawyerBasket.ProfileService.Domain.Entities.Contact", "LawyerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LawyerProfile");
                });

            modelBuilder.Entity("LawyerBasket.ProfileService.Domain.Entities.Experience", b =>
                {
                    b.HasOne("LawyerBasket.ProfileService.Domain.Entities.LawyerProfile", "LawyerProfile")
                        .WithMany("Experience")
                        .HasForeignKey("LawyerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LawyerProfile");
                });

            modelBuilder.Entity("LawyerBasket.ProfileService.Domain.Entities.LawyerExpertisement", b =>
                {
                    b.HasOne("LawyerBasket.ProfileService.Domain.Entities.Expertisement", "Expertisement")
                        .WithMany("lawyerExpertisement")
                        .HasForeignKey("ExpertisementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LawyerBasket.ProfileService.Domain.Entities.LawyerProfile", "LawyerProfile")
                        .WithMany("LawyerExpertisements")
                        .HasForeignKey("LawyerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expertisement");

                    b.Navigation("LawyerProfile");
                });

            modelBuilder.Entity("LawyerBasket.ProfileService.Domain.Entities.LawyerProfile", b =>
                {
                    b.HasOne("LawyerBasket.ProfileService.Domain.Entities.UserProfile", "UserProfile")
                        .WithOne("LawyerProfile")
                        .HasForeignKey("LawyerBasket.ProfileService.Domain.Entities.LawyerProfile", "UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("LawyerBasket.ProfileService.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("LawyerBasket.ProfileService.Domain.Entities.Gender", "Gender")
                        .WithMany("UserProfile")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("LawyerBasket.ProfileService.Domain.Entities.City", b =>
                {
                    b.Navigation("Address");
                });

            modelBuilder.Entity("LawyerBasket.ProfileService.Domain.Entities.Expertisement", b =>
                {
                    b.Navigation("lawyerExpertisement");
                });

            modelBuilder.Entity("LawyerBasket.ProfileService.Domain.Entities.Gender", b =>
                {
                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("LawyerBasket.ProfileService.Domain.Entities.LawyerProfile", b =>
                {
                    b.Navigation("Academy");

                    b.Navigation("Certificates");

                    b.Navigation("Contact");

                    b.Navigation("Experience");

                    b.Navigation("LawyerExpertisements");
                });

            modelBuilder.Entity("LawyerBasket.ProfileService.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("LawyerProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
